// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Strip any stray non-ASCII characters (e.g. a leading BOM / zero-width no-break
// space, U+FEFF) that can slip into the Vercel/.env value on copy-paste. Such a
// character corrupts the `apikey` and `Authorization` headers and makes EVERY
// Supabase request throw: "Failed to read the 'headers' property from 'RequestInit':
// String contains non ISO-8859-1 code point." A Supabase URL and anon key are always
// plain ASCII, so this is safe.
const cleanEnv = (v: string | undefined) => (v ?? "").replace(/[^\x20-\x7E]/g, "").trim();
// Exported so direct `fetch` calls to edge functions (file uploads that can't use
// supabase-js) reuse the SAME sanitized values — otherwise a BOM in the Vercel env
// var corrupts the URL/headers and the upload fails with a 405 / empty JSON body.
export const SUPABASE_URL = cleanEnv(import.meta.env.VITE_SUPABASE_URL);
export const SUPABASE_PUBLISHABLE_KEY = cleanEnv(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});